version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - restore_cache:
          keys: 
            - gradle-{{ checksum "build.gradle" }}
      - run: gradle clean
      - run: gradle assemble
      - run: gradle test
      # - save_cache:
      #     paths:
      #       - .gradle
      #       key: gradle-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: build/distributions
          destination: distributions
      - store_artifacts:
          path: build/libs
          destination: libs
  deploy:
    machine:
      enabled: true
    environment:
      HEROKU_APP: repair-invoice-system-api
    steps:
      - checkout
      - run:
          name: Deploy Project to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master
# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filter:
#             branches:
#               only: sequential-branch-filter